version: '3.7'
services:
  web:
    build: ./app
    environment:
      - DOCKER=True
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=db:5432
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - web
    links:
      - web:web
